# Travis-CI config

language: cpp
dist: trusty
compiler:
  - clang
os:
  - linux
  
before_install:
  - echo $TRAVIS_BUILD_DIR
  - sudo apt-get install g++-multilib lib32z1-dev
  - mkdir $HOME/sourcemod
  - mkdir $HOME/metamod-source

install:
  - cd $HOME/sourcemod
  - ls
  - git clone --depth 1 --recurse-submodules -j8 --shallow-submodules -b 1.10-dev https://github.com/alliedmodders/sourcemod.git .
  - ls
  - cp -r $TRAVIS_BUILD_DIR $HOME/
  - cd $HOME/metamod-source
  - ls
  - git clone --depth 1 --recurse-submodules -j8 --shallow-submodules -b 1.11-dev https://github.com/alliedmodders/metamod-source.git .
  - ls

script:
- cd $HOME/SMbz2
- ls
- make
- cd Release
- mkdir build
- mv smbz2.ext.so build
- tar czvf SMbz2-${TRAVIS_TAG}-linux.tar.gz build

deploy:
  provider: releases
  api_key: ${GH_DEPLOYTOKEN}
  file_glob: true
  file: "SMbz2-${TRAVIS_TAG}-linux.tar.gz"
  skip_cleanup: true
  on:
    tags: true