# Travis-CI config

language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
os:
  - linux
branches:
  only:
    - master

# Use IRC notifications instead of email
notifications:
  email: false

before_install:
  - echo $TRAVIS_BUILD_DIR
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++ gcc-multilib g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev
  - mkdir $HOME/sourcemod
  - mkdir $HOME/mmsource-1.10

install:
  - cd $HOME/sourcemod
  - git clone -b 1.10-dev --single-branch https://github.com/alliedmodders/sourcemod.git .
  - cp -r $TRAVIS_BUILD_DIR $HOME/sourcemod/extensions/
  - cd $HOME/mmsource-1.10
  - git clone -b 1.10-dev --single-branch https://github.com/alliedmodders/metamod-source.git .

script:
- cd $HOME
- make